import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

const styles = StyleSheet.create({
  backgroundImage: {
    flex: 1,
    resizeMode: 'cover',
  },
  container: {
    flex: 1,
    alignItems: 'stretch',
    justifyContent: 'center',
    backgroundColor: 'rgba(0,0,0,0.4)',
    position: 'relative',
    paddingTop: 50,
    paddingHorizontal: 18,
  },
  logoContainer: {
    alignItems: 'center',
    marginBottom: 30,
  },
  logoWrapper: {
    width: 150,
    height: 150,
    borderRadius: 75,
    backgroundColor: 'rgba(253, 253, 253, 0.95)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  logo: {
    width: 150,
    height: 150,
  },
  title: {
    fontSize: 32,
    fontWeight: '900',
    color: '#ffffff',
    marginBottom: 30,
    textShadowColor: 'rgba(0,0,0,0.8)',
    textShadowOffset: { width: 0, height: 3 },
    textShadowRadius: 6,
    letterSpacing: 1,
    textAlign: 'center',
  },
  card: {
    width: width * 0.9,
    backgroundColor: 'rgba(245, 237, 237, 0.95)',
    borderRadius: 24,
    padding: 30,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.25,
    shadowRadius: 20,
    elevation: 15,
    marginBottom: 20,
    backdropFilter: 'blur(10px)',
    borderWidth: 10,
    borderColor: '#01763C',
  },
  subtitle: {
    fontSize: 22,
    fontWeight: '700',
    marginBottom: 25,
    color: '#2c3e50',
    textAlign: 'center',
    letterSpacing: 0.3,
  },
  icon: {
    width: 24,
    height: 24,
    tintColor: '#667eea',
    marginBottom: 15,
  },
  inputGroup: {
    width: '100%',
    marginBottom: 20,
  },
  inputLabel: {
    fontSize: 14,
  searchBar: {
    backgroundColor: '#fcfcfcff',
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 8,
    fontSize: 16,
    marginBottom: 12,
    marginTop: 8,
    width: '100%',
    alignSelf: 'stretch',
    marginHorizontal: -18,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
    fontWeight: '600',
    color: '#34495e',
    marginBottom: 8,
    marginLeft: 4,
  },
  input: {
    width: '100%',
    height: 56,
    borderWidth: 2,
    borderColor: '#e9ecef',
    borderRadius: 16,
    paddingHorizontal: 20,
    backgroundColor: '#f8f9fa',
    fontSize: 16,
    color: '#2c3e50',
    fontWeight: '500',
  },
  inputFocused: {
    borderColor: '#667eea',
    backgroundColor: '#ffffff',
    shadowColor: '#667eea',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  button: {
    width: '100%',
    backgroundColor: '#38E078',
    paddingVertical: 18,
    borderRadius: 16,
    alignItems: 'center',
    marginTop: 20,
    shadowColor: '#12250eff',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 6,
  },
  buttonPressed: {
    backgroundColor: '#5a6fd8',
    transform: [{ scale: 0.98 }],
  },
  buttonDisabled: {
    opacity: 0.5,
    backgroundColor: '#a5d6a7',
  },
  buttonText: {
    color: '#01763C',
    fontSize: 18,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  checkbox: {
    width: 22,
    height: 22,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: '#01763C',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff'
  },
  checkboxChecked: {
    backgroundColor: '#01763C',
    borderColor: '#01763C',
  },
decorativeCircle: {
    position: 'absolute',
    borderRadius: 100,
  },
  circle1: {
    top: -50,
    left: -50,
    width: 200,
    height: 200,
    backgroundColor: 'rgba(144,238,144,0.2)',
  },
  circle2: {
    bottom: -80,
    right: -80,
    width: 150,
    height: 150,
    borderRadius: 75,
    backgroundColor: 'rgba(50,205,50,0.15)',
  },
});

export default styles;
